### ISSUE TITLE
Decide on what identifier to use for Organizations (URA?) in FHIR-resources

### ISSUE THREAD

**Issue by jorritspee** [SanteonNL/shared-care-planning#11]
We don't want to use did's

- [ ] can we get an URAcredential?
- [ ] separate credential or part of organizationcredential?
- [ ] reuse stuff of Mitz x Nuts?

**Comment by bramwesselo** [comment]
Let's not use 'URA' here as it is a Dutch identifier. Changed it to a more generic 'Organization credential'
