### ISSUE TITLE
Create slides that show alignment with NVS

### ISSUE THREAD

**Issue by jorritspee** [SanteonNL/shared-care-planning#15]
Links to:
- “Data is beschikbaar voor alle betrokkenen in het zorgnetwerk van een burger en voor de burger zelf” 
- “Plateau 2: Ondersteuning van netwerkzorg”:

**Comment by bramwesselo** [comment]
added a slide in slidedeck: https://github.com/SanteonNL/shared-care-planning/blob/main/input/attachments/Shared%20Care%20Planning%20voor%20Zorg&ICT2024.pptx
